version: '3'
services:
  react-app:
    image: react-client
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  api-server:
    image: api-server
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}

networks:
  mern-app:
    driver: bridge
